/**
 * Lane Q: the place icon set — one 12×12 pixel icon for each of the 25 places of the campus
 * (lane H's leftover: the Game Menu, the facility windows and the Construction Board showed
 * emoji, which look different on every OS). Same manner as icons.ts: a character grid with a
 * legend, painted with a dark rim. Pure and deterministic; bits.tsx-style rendering lives in
 * ui/late/PlaceIcon.tsx (the emoji stays as the fallback where no canvas draws, e.g. tests).
 */
import { createBitmap, hex, outline, set, type Bitmap } from './bitmap'
import type { PlaceId } from '../world/lobbyMap'

interface PlaceIconDef {
  rows: string[]
  legend: Record<string, string>
  /** The emoji it replaces (the fallback). */
  glyph: string
}

const RIM = '#1a1030'

export const PLACE_ICONS: Record<PlaceId, PlaceIconDef> = {
  kitchen: {
    glyph: '🍲',
    legend: { s: '#dcd4ec', k: '#4a4f58', o: '#f0a040', m: '#7a808a', l: '#c8ced8', d: '#3a3f48' },
    rows: [
      '...s...s....',
      '..s...s...s.',
      '...s...s..s.',
      '............',
      'kkkkkkkkkkkk',
      '.oooooooooo.',
      '.mmmmmmmmmm.',
      '.mlmmmmmmmm.',
      '.mlmmmmmmmm.',
      '.mmmmmmmmmm.',
      '..mmmmmmmm..',
      '...d....d...',
    ],
  },
  tacticalCenter: {
    glyph: '🗺',
    legend: { p: '#e8d8b0', d: '#a8946a', g: '#5fb07a', b: '#4a8ad0', r: '#e04a4a', w: '#7a5030' },
    rows: [
      'w..........w',
      'pppppppppppp',
      'pggpppdppbbp',
      'pgggpdpppbbp',
      'ppggppprpbpp',
      'pppppdrrrppp',
      'ppdpdpprpppp',
      'pdpppppppggp',
      'ppbbpppdpggp',
      'pbbbppdppppp',
      'pppppppppppp',
      'w..........w',
    ],
  },
  promotionChamber: {
    glyph: '⛩',
    legend: { r: '#d04030', d: '#8a2420', g: '#f2c75c', s: '#8a8496' },
    rows: [
      'rrrrrrrrrrrr',
      '.dddddddddd.',
      '..r......r..',
      'rrrrrrrrrrrr',
      '..r..gg..r..',
      '..r.gggg.r..',
      '..r..gg..r..',
      '..r......r..',
      '..r......r..',
      '..r......r..',
      '..d......d..',
      '.sss....sss.',
    ],
  },
  trainingCenter: {
    glyph: '⚔',
    legend: { b: '#d8deee', d: '#8a90a8', h: '#7a5030', g: '#f2c75c' },
    rows: [
      'b..........b',
      'bb........bb',
      '.bb......bb.',
      '..bd....db..',
      '...bd..db...',
      '....bddb....',
      '....dbbd....',
      '...gd..dg...',
      '..gg....gg..',
      '.hh......hh.',
      'hh........hh',
      'h..........h',
    ],
  },
  transferStation: {
    glyph: '⇄',
    legend: { c: '#36a7c9', l: '#9ae0f0', m: '#b77be0' },
    rows: [
      '............',
      '......c.....',
      '......cc....',
      'cccccccccc..',
      'llllllllccc.',
      '......cc....',
      '....mm......',
      '...mmm......',
      '.mmmmmmmmmm.',
      '..mmmmmmmmmm',
      '....mm......',
      '............',
    ],
  },
  shop: {
    glyph: '♦',
    legend: { a: '#6ad8e8', l: '#cff6ff', d: '#2a8aa0' },
    rows: [
      '....aaaa....',
      '...alllaa...',
      '..alllaaaa..',
      '.allaaaaaaa.',
      'aaaaaaaaaaaa',
      'ddaaaaaaaadd',
      '.ddaaaaaadd.',
      '..ddaaaadd..',
      '...ddaadd...',
      '....dddd....',
      '.....dd.....',
      '............',
    ],
  },
  hallOfMagic: {
    glyph: '✶',
    legend: { v: '#8b6cf0', l: '#e0d4ff', s: '#fff6c0' },
    rows: [
      '.....v......',
      '.....vv.....',
      's...vlv....s',
      '...vvlvv....',
      'vvvvllllvvvv',
      '.vvllssllvv.',
      '..vvllllvv..',
      '...vvllvv...',
      '..vv.vv.vv..',
      '.vv..v...vv.',
      'v....v....v.',
      's.........s.',
    ],
  },
  rift: {
    glyph: '⟡',
    legend: { v: '#3a2a6a', p: '#c050ff', l: '#ffc0ff', w: '#ffffff' },
    rows: [
      '.....p......',
      '....pp......',
      '....pvp.....',
      '...pvvp.....',
      '...pvlvp....',
      '..pvlwlp....',
      '..pvlwlvp...',
      '...pvlvvp...',
      '...pvvvp....',
      '....pvp.....',
      '....pp......',
      '....p.......',
    ],
  },
  guild: {
    glyph: '⚑',
    legend: { w: '#7a5030', b: '#4a74c0', l: '#8ab0f0', g: '#fff0a0' },
    rows: [
      'w...........',
      'wbbbbbbbbb..',
      'wbllbbbbbbb.',
      'wbbbbggbbbb.',
      'wbbbggggbbb.',
      'wbbbbggbbbb.',
      'wbbbbbbbbb..',
      'wbbbb.bbbb..',
      'wbb.....bb..',
      'w...........',
      'w...........',
      'ww..........',
    ],
  },
  synthesis: {
    glyph: '⚗',
    legend: { g: '#c8d0e0', p: '#c04a8a', l: '#ff9ad0', b: '#ffffff' },
    rows: [
      '....gggg....',
      '.....gg.....',
      '.....gg.....',
      '.....gg..b..',
      '....gppg....',
      '...gplppg...',
      '..gpplpppg..',
      '.gppppppppg.',
      'gpplppppppg.',
      'gppppppplppg',
      '.gppppppppg.',
      '..gggggggg..',
    ],
  },
  armory: {
    glyph: '⚒',
    legend: { m: '#7a808a', l: '#c8ced8', d: '#3a3f48', w: '#8a5a30', o: '#ff8a3a' },
    rows: [
      '.mmmm.......',
      'mlllmm......',
      '.mmmmw......',
      '.....ww.....',
      '......ww..o.',
      '.......w.o..',
      '.dddddddddd.',
      'mlllllllllld',
      '.mmmmmmmmmd.',
      '....mmmd....',
      '...mmmmmd...',
      '..dddddddd..',
    ],
  },
  daily: {
    glyph: '🌀',
    legend: { b: '#4a8ad0', l: '#9ad4ff', w: '#ffffff' },
    rows: [
      '...bbbbbb...',
      '..bb....bb..',
      '.bb..lll..b.',
      '.b..l...l.b.',
      'bb.l..ww.lb.',
      'b..l.w..l.b.',
      'b..l..w.l.b.',
      'b...l...lbb.',
      'bb...lll.b..',
      '.b......bb..',
      '.bb...bbb...',
      '...bbbb.....',
    ],
  },
  summon: {
    glyph: '🔮',
    legend: { p: '#9a6af0', l: '#e0c8ff', w: '#ffffff', g: '#f2c75c', d: '#a8862a' },
    rows: [
      '...pppppp...',
      '..pllpppppp.',
      '.plwlpppppp.',
      '.pllpppppppp',
      'ppppppppppp.',
      'pppppppppppp',
      '.pppppppppp.',
      '..pppppppp..',
      '...pppppp...',
      '..gggggggg..',
      '.gddddddddg.',
      'gggggggggggg',
    ],
  },
  roster: {
    glyph: '📜',
    legend: { p: '#e8d8b0', d: '#a8946a', i: '#5a4a30', r: '#c04040' },
    rows: [
      '.dddddddddd.',
      'dppppppppppd',
      '.pppppppppp.',
      '.piiipiiiip.',
      '.pppppppppp.',
      '.piiiiipiip.',
      '.pppppppppp.',
      '.piipiiiiip.',
      '.pppppppprr.',
      '.ppppppppprr',
      'dppppppppppd',
      '.dddddddddd.',
    ],
  },
  party: {
    glyph: '🛡',
    legend: { b: '#4a74c0', l: '#8ab0f0', g: '#f2c75c', d: '#24447a' },
    rows: [
      'gggggggggggg',
      'gbbbbbbbbbbg',
      'gbllbbgbbbbg',
      'gblbbbgbbbbg',
      'gbbbgggggbbg',
      'gbbbbbgbbbbg',
      'gbbbbbgbbbdg',
      '.gbbbbgbbdg.',
      '.gbbbbbbbdg.',
      '..gbbbbbdg..',
      '...gbbbdg...',
      '....gggg....',
    ],
  },
  tower: {
    glyph: '🗼',
    legend: { s: '#9a92a6', d: '#5a5462', y: '#ffd27a', r: '#d04030' },
    rows: [
      '.....rr.....',
      '.....r......',
      '....sss.....',
      '...sssss....',
      '....sys.....',
      '....sss.....',
      '...ssyss....',
      '...sssss....',
      '...syssd....',
      '..ssssssd...',
      '..sssysssd..',
      '.ddddddddd..',
    ],
  },
  fairy: {
    glyph: '✧',
    legend: { w: '#bfe6ff', l: '#ffffff', s: '#f0c8a0', p: '#ff9ad0' },
    rows: [
      '.ww.....ww..',
      'wllw...wllw.',
      'wlllw.wlllw.',
      '.wllwswllw..',
      '..wwsssww...',
      '....sss.....',
      '...wpppw....',
      '..wllpllw...',
      '..wlwpwlw...',
      '...w.p.w....',
      '.....p......',
      '....p.p.....',
    ],
  },
  dormitory: {
    glyph: '🛏',
    legend: { w: '#7a5030', l: '#fff6e0', b: '#5b86d6', d: '#3a5a9a' },
    rows: [
      '............',
      'w...........',
      'w...........',
      'wll.........',
      'wlllbbbbbbb.',
      'wbbbbbbbbbbb',
      'wddddddddddw',
      'wwwwwwwwwwww',
      'w..........w',
      'w..........w',
      '............',
      '............',
    ],
  },
  tavern: {
    glyph: '🍺',
    legend: { f: '#fff6e0', a: '#f0a030', d: '#b06a18', w: '#8a5a30', l: '#c8905a' },
    rows: [
      '..ffff......',
      '.ffffff.....',
      '.waaaaw.....',
      '.waaaaww....',
      '.wdaaaw.w...',
      '.waaaaw.w...',
      '.wadaaw.w...',
      '.waaaaww....',
      '.waaaaw.....',
      '.wlllllw....',
      '.wwwwwww....',
      '............',
    ],
  },
  infirmary: {
    glyph: '✚',
    legend: { w: '#f4f4f8', r: '#d0302a', d: '#a02020' },
    rows: [
      '.wwwwwwwwww.',
      'wwwwwwwwwwww',
      'wwwwrrrrwwww',
      'wwwwrrrrwwww',
      'wrrrrrrrrrrw',
      'wrrrrrrrrrrw',
      'wrrrrrrrrrrw',
      'wdddrrrrdddw',
      'wwwwrrrrwwww',
      'wwwwddddwwww',
      'wwwwwwwwwwww',
      '.wwwwwwwwww.',
    ],
  },
  garden: {
    glyph: '🌱',
    legend: { g: '#5aae4e', d: '#2e7a3a', b: '#6e4a2a', p: '#e05a7a' },
    rows: [
      '.......pp...',
      '..gg..pppp..',
      '.gggg..pp...',
      '.ggdg..d....',
      '..gdgg.d.gg.',
      '...dggdggg..',
      '....dddgg...',
      '......d.....',
      '......d.....',
      '.bbbbbbbbbb.',
      'bbbbbbbbbbbb',
      '.bbbbbbbbbb.',
    ],
  },
  memorial: {
    glyph: '🕯',
    legend: { y: '#ffd27a', o: '#ff8a3a', w: '#f0ecf6', g: '#c4bed0', d: '#8a8496' },
    rows: [
      '.....y......',
      '....yoy.....',
      '....yoy.....',
      '.....o......',
      '....www.....',
      '...wwwgw....',
      '...wwwgw....',
      '...wwwgw....',
      '...wwwgw....',
      '...wwwgw....',
      '..dddddddd..',
      '.dddddddddd.',
    ],
  },
  library: {
    glyph: '📚',
    legend: { r: '#b04040', b: '#4a74c0', g: '#4a9a5a', y: '#d8b040', p: '#fff6e0', w: '#7a5030' },
    rows: [
      '............',
      '.rr.........',
      '.rr.bb......',
      '.rr.bb.gg...',
      '.ry.bb.gg.yy',
      '.rr.by.gg.yy',
      '.rr.bb.gy.yy',
      '.rr.bb.gg.yy',
      '.rr.bb.gg.yy',
      'wwwwwwwwwwww',
      'w..........w',
      '............',
    ],
  },
  watchtower: {
    glyph: '🔭',
    legend: { g: '#d8b040', d: '#8a6a1a', s: '#c8ced8', w: '#7a5030' },
    rows: [
      '..........ss',
      '........ggss',
      '......gggg..',
      '....ggggd...',
      '..ggggdd....',
      'ssggdd......',
      'ss.d.w......',
      '....w.w.....',
      '...w...w....',
      '..w.....w...',
      '.w.......w..',
      'w.........w.',
    ],
  },
  market: {
    glyph: '⚖',
    legend: { g: '#f2c75c', d: '#a8862a', w: '#7a5030' },
    rows: [
      '.....gg.....',
      'gggggggggggg',
      'd....gg....d',
      'd....gg....d',
      'd....gg....d',
      'dd...gg...dd',
      'ddd..gg..ddd',
      'gggg.gg.gggg',
      '.....gg.....',
      '.....gg.....',
      '...wwwwww...',
      '..wwwwwwww..',
    ],
  },
}

/** Paint a place icon (14×14 with its rim). Pure. */
export function placeIconBitmap(place: PlaceId): Bitmap {
  const def = PLACE_ICONS[place]
  const h = def.rows.length
  const w = Math.max(...def.rows.map((r) => r.length))
  const b = createBitmap(w + 2, h + 2)
  for (let y = 0; y < h; y++) {
    const row = def.rows[y]!
    for (let x = 0; x < row.length; x++) {
      const ch = row[x]!
      if (ch === '.') continue
      const c = def.legend[ch]
      if (!c) throw new Error(`placeIconBitmap: '${place}' has no colour for '${ch}'`)
      set(b, x + 1, y + 1, hex(c))
    }
  }
  return outline(b, hex(RIM))
}

/** The silhouette of a place icon (the test: no two places share one). */
export function placeIconMask(place: PlaceId): string {
  return PLACE_ICONS[place].rows.map((r) => r.replace(/[^.]/g, '#')).join('/')
}
